### ISSUE TITLE
Agregar nueva entrada

### ISSUE THREAD

**Issue by naberz95** [naberz95/BlogPersonalNaberz#1]
Elaborar una nueva entrada sobre compuertas lógicas

**Comment by naberz95** [comment]
Porfavor añadir una entrada en el blog

**Comment by introSoft-iud** [comment]
Acabo de fixed  #1, agregé mas contenido

**Comment by introSoft-iud** [comment]
Tarea fie relaizada en 11c06b29ce16f3c6ec59fc01e8a933422acd2169
